pkg/slayers/scion_spec.gobra

Gobra did not report this when executing it with `moreCompleteExhale`

Fix issue reported by Marco

---

pkg/slayers/extn.go
pkg/slayers/extn_spec.gobra

The only methods in extn.go missing are `decodeEndToEndExtn` and `decodeHopByHopExtn`. These are to be handled with the remaining methods in isse #77

Lift assumptions from `extn.go`

---

pkg/slayers/path/scion/base.go
pkg/slayers/path/scion/base_spec.gobra
pkg/slayers/path/scion/decoded.go
pkg/slayers/path/scion/raw.go
pkg/slayers/scion.go
pkg/slayers/scmp.go
pkg/slayers/scmp_msg.go
verification/dependencies/github.com/google/gopacket/writer.gobra

There are still a few magic wands that need to be dealt with in slayers/scion.go (i.e., for methods `SetSrcAddr` and `packAddr`), but addressing this requires a more drastic change. It will be done in a separate PR

drop usages of wands that are not strictly necessary (for carbon)

---

pkg/slayers/path/scion/base.go
pkg/slayers/path/scion/raw.go
pkg/slayers/path/scion/raw_spec.gobra
pkg/slayers/scion_spec.gobra
router/dataplane.go
router/dataplane_spec.gobra

This PR proves the memory safety of `process` (except for one small branch for which memory safety will be proven on a separate PR, together with the functional spec that is missing - mostly about the values of type `processResult` that are returned). Ofc, all of this depends on `packSCMP` for which no spec is currently assumed. When that method is finished, we should remove all `def.TODO()` to make sure that the given spec is as permissive as expected

finish `process`

---

pkg/slayers/scion.go
pkg/slayers/scion_spec.gobra
router/dataplane.go
verification/dependencies/net/ip.gobra
verification/utils/definitions/definitions.gobra

This is currently blocked on an incompletness from silicon due to unnecessary usage of non-linear IA. There is also a verification error that I need to solve in the dataplane, but that is, for the most part, changing the permission amounts. I will address all of it after Marco solves the causes of the incompletness. Nonetheless, I guess the code can be reviewed already

Verify `AddHdrLen`

---

pkg/slayers/scion.go
router/dataplane.go

As made clear recently, one may easily generate non-linear proof obligations when doing nested unfoldings of wildcard permissions. There is currently an optimization that Marco is working on. In the meanwhile, we can remove all unecessary wildcards from unfoldings to ensure that we are already obtaining the most stable proof we can for the dataplane

Remove wildcard perm in unfoldings

---

verification/io/dataplane_abstract.gobra
verification/io/io-spec.gobra
verification/io/other_defs.gobra
verification/io/router.gobra
verification/io/router_events.gobra
verification/io/segment-defs.gobra
verification/io/xover.gobra

The IO-spec is rewritten such that it depends on an abstract verison of the dataplane. This is needed to provide additional ghost state. Also the IO-spec uses now the match clause, making  it easier to read and a closer match to the IO-spec from Isabelle. Finally, all unrequired functions are commented out.

Adding DataPlaneSpec to the IO-spec

---

.gitignore
private/underlay/conn/conn.go
private/underlay/conn/conn_spec.gobra
router/assumptions.gobra
router/dataplane.go
router/dataplane_spec.gobra
router/svc_spec.gobra
verification/dependencies/errors/errors_spec.gobra
verification/dependencies/github.com/google/gopacket/writer.gobra
verification/dependencies/golang.org/x/net/internal/socket/socket.gobra
verification/dependencies/golang.org/x/net/ipv4/endpoint.gobra
verification/dependencies/golang.org/x/net/ipv6/endpoint.gobra
verification/dependencies/net/net.gobra
verification/dependencies/net/udpsock.gobra
verification/dependencies/syscall/syscall_unix.gobra
verification/utils/floats/floats.gobra

Depends on https://github.com/viperproject/gobra/pull/700/files

Dependencies of `Run`

---

verification/io/io-spec.gobra

- Added missing clause in the `up2down` guard.
- Fixed `traversedseg` in the `enter` guard.
- Improved convenience of helper functions `establishGuardTraversedseg()` and `establishGuardTraversedsegInc()`.

IO-Spec fix

---

router/dataplane.go

Due to an incompleteness in the packaging algorithm of Silicon, `addEndhostPort` could not be verified and was made `trusted`. This incompleteness was solved recently. This PR makes that function verified.

Make method `addEndhostPort` not trusted

---

router/dataplane.go

After merging https://github.com/viperproject/gobra/pull/732, this assumption is no longer necessary.

Drop assumption of non-nilness of a closure

---

router/dataplane_spec_test.gobra
router/io-spec.gobra
verification/io/dataplane_abstract.gobra

This PR contains a test that allocates a `DataPlane`, sets it up, and then calls the `Run` method. In the interest of time, I did not add a specification to the setters. Instead, I performed the set-up by assigning to the (private) fields directly, as my goal was to have a proof that we can establish the preconditions of `Run` right after allocation.

Add test that sets up a dataplane and runs it

---

router/dataplane.go
router/io-spec.gobra

- Fixed mistake in Asid extraction function
- Added additional postconditions in `HopfieldsConsDir()` and `HopfieldsNotConsDir()`
- Added pre/postconditions for `process`
- Added `DpAgreesWithSpec()` to `processPkt()`, `processSCION()` and `process()`

Updated IO-Spec-Function to Correlate Bytes with Terms

---

verification/io/router.gobra
verification/io/router_events.gobra

- Removed link validity check from `dp2_forward_ext_guard`.
- Split `dp3s_forward_ext` into two distinct cases: one verifies link validity (enter event), while the other does not (xover event).

Refined IO-Spec

---

pkg/experimental/epic/epic.go
pkg/slayers/scion_spec.gobra
verification/dependencies/crypto/aes/cipher.gobra
verification/dependencies/crypto/cipher/cbc.gobra
verification/dependencies/crypto/cipher/cipher.gobra

Due to perf. problems, we cannot merge #261 at the moment. Nonetheless, there is no reason why we can't make the changes to the dependencies

Bring changes of `libepic` from PR #261

---

.github/workflows/gobra.yml

The master branch is breaking because verification with the `z3API` broke. For now, I am disabling it

Disable `z3API`

---

.github/workflows/gobra.yml

It seems that we have some kind of performance regression in silicon that causes the package `experimental/epic` to timeout. This PR bumps, for now, the timeout so that we can continue making progress while we figure out what caused this.

Increase timeout for the `experimental/epic` package

---

router/dataplane_concurrency_model.gobra
verification/io/io-spec.gobra

This should improve performance, especially considering that triggers with resources tend to cause big slowdowns in Gobra/silicon. On the other hand, this requires slightly more annotations, as we need to explicitly trigger the bodies with calls to the `Trigger*` functions, e.g., `TriggerBodyIoEnter`.

Use artificial triggers for quantifiers inside IO resources

---

pkg/slayers/path/hopfield_spec.gobra
pkg/slayers/path/infofield_spec.gobra
router/dataplane.go
router/io-spec.gobra

- moved `absInfofield` functions from `hopfield_spec.gobra`to` infofield_spec.gobra`
- added opaque to `absPkt` and subsequent functions

AbsPkt improvements

---

pkg/slayers/path/scion/base.go
pkg/slayers/path/scion/base_spec.gobra
pkg/slayers/path/scion/raw.go
pkg/slayers/path/scion/raw_spec.gobra
pkg/slayers/scion_spec.gobra
verification/utils/bitwise/proofs.dfy
verification/utils/definitions/definitions.gobra

This PR proves a few lemma in the `path/scion` package and performs some clean-up: we introduce `DecodeFromSpec` and `SerializeToSpec` for shortening specifications and allowing re-use and we drop the lemma `RawIdxPerm`. Even though this was useful in previous versions of silicon to keep verification time low, this is no longer necessary and this lemma is non-versatile: small changes to the call-place may require significant changes to the lemma

Prove IO lemmas in `path/scion`

---

.github/workflows/gobra.yml

I am disabling it for now. I want to understand if any of the proof obligations of #284 are currently failing because of this.

Update gobra.yml to disableNL

---

router/io-spec-abstract-transitions.gobra
router/io-spec-atomic-events.gobra
verification/io/bios.gobra
verification/io/io-spec.gobra
verification/io/router.gobra
verification/io/router_events.gobra
verification/io/xover.gobra

This PR updates the IO-spec to reflect the latest changes to the IO spec. In particular, the `xover_core` event is now completely dropped.

Update IO-spec to drop the `xover_core` event

---

pkg/slayers/path/hopfield_spec.gobra
pkg/slayers/path/infofield.go
pkg/slayers/path/infofield_spec.gobra
pkg/slayers/path/io_msgterm_spec.gobra
router/dataplane.go
verification/io/router.gobra

I also fixed the indexes of the mac in `BytesToIO_HF`

Streamline the assumptions about `MsgTerm`s

---

router/dataplane.go
router/svc.go
verification/dependencies/sync/mutex.gobra

Prove that, modulo infinite blocking, there are no terminations issues. This does not imply that everything terminates, but it ensures that, if all blocking operations eventually unblock, then processing all individual packets definitely terminates (i.e., there are no infinite loops or infinite recursion)

Add checks for termination modulo blocking

---

pkg/slayers/path/scion/base_spec.gobra
pkg/slayers/path/scion/raw.go
pkg/slayers/path/scion/raw_spec.gobra
router/dataplane.go
router/io-spec-abstract-transitions.gobra
router/io-spec-non-proven-lemmas.gobra
router/io-spec.gobra
verification/io/router.gobra
verification/io/router_events.gobra

- Updated IO-spec for link check logic
- proof of link check logic in `process()`
TODO:

 IO-spec update for link check logic

---

router/io-spec-abstract-transitions.gobra
router/io-spec-atomic-events.gobra
router/io-spec.gobra
verification/io/bios.gobra
verification/io/io-spec.gobra
verification/io/other_defs.gobra
verification/io/router.gobra
verification/io/router_events.gobra
verification/io/xover.gobra

Minor renamings and merged functions to simplify the IO-spec. 
Changes include:
- Renamed `dp3s_iospec_bio3s_xover_up2down` to `dp3s_iospec_bio3s_xover`.
- Renamed `dp2_check_interface` to `dp2_enter_interface`.
- Renamed `PeerOrCore` to `Core`.
- Renamed `xover_up2down2_link_type` to `xover2_link_type`.
- Additionally, functions related to the xover guard have been merged into a single `dp2_xover_guard` including the link check.

Update names of functions according to the changes in the IO-spec

---

pkg/slayers/path/hopfield_spec.gobra
router/dataplane.go
router/dataplane_spec.gobra
router/dataplane_spec_test.gobra
router/io-spec-abstract-transitions.gobra
router/io-spec-non-proven-lemmas.gobra
router/io-spec.gobra

Proves that packets can no longer bounce internally after the fix in https://github.com/scionproto/scion/pull/4502.

Proof of Internal Packet Bouncing fix (#4502)

---

pkg/slayers/path/infofield_spec.gobra
pkg/slayers/path/scion/base_spec_test.gobra
pkg/slayers/path/scion/raw.go
pkg/slayers/path/scion/raw_spec.gobra
pkg/slayers/scion_spec.gobra
router/dataplane.go
router/io-spec-abstract-transitions.gobra
router/io-spec-lemmas.gobra
router/io-spec.gobra
router/widen-lemma.gobra

- removes `dp io.DataPlaneSpec` arg from both `absPkt()` functions
- merges `headerOffset` and `MetaLen` into `headerOffsetWithMetaLen` to remove the ghost var in `infofield_spec.gobra`

Refactoring of absPkt

---

pkg/slayers/path/scion/base_spec.gobra
pkg/slayers/path/scion/decoded.go

With the fix introduced in https://github.com/viperproject/gobra/pull/768, we no longer have to introduce the types `AbsBase` and `AbsMetaHdr`. This provides ample opportunity for simplification

Simplify path/scion

---

pkg/slayers/path/scion/info_hop_setter_lemmas.gobra

Use tabs for indentation, which is the idiomatic way in Go.
(changes done originally in #352)

Format `info_hop_setter_lemmas.gobra`

---

pkg/slayers/scion_spec.gobra
router/dataplane.go

It establishes that a SCION pkt retains its status as a SCION pkt through the `process()` method.

Drop assumptions of `IsSupportedPkt` in `process`

---

.github/workflows/gobra.yml
pkg/slayers/path/scion/base_spec.gobra
pkg/slayers/path/scion/decoded.go
pkg/slayers/path/scion/decoded_spec.gobra
pkg/slayers/path/scion/raw.go
pkg/slayers/path/scion/raw_spec.gobra
pkg/slayers/scion_spec.gobra
router/dataplane.go
router/dataplane_test.go

Based on https://github.com/scionproto/scion/pull/4556
Superseds #364

Drop two assumptions and merge validity criteria `StronglyValid` and `FullyValid`

---

router/dataplane.go

This assertion helps Silicon to prove the corresponding invariant.

New assertion in `Run()` to resolve verification error

---

verification/dependencies/crypto/aes/cipher.gobra

The block size of AES is not dependent on the key size. It is 16 bytes for all key sizes.

correct BlockSize in aes NewCipher spec 

---

pkg/slayers/path/scion/raw.go
pkg/slayers/path/scion/raw_spec.gobra
router/dataplane.go
router/io-spec-lemmas.gobra

Based on #387. Turns out that the proof of `doXover` is rightly rejected in the new semantics, and the reason it was accepted in the first place was due to an unsoundness in silicon (https://github.com/viperproject/silicon/issues/894). Despite the old proof being wrongly accepted, the specs are true, and thus, this unsoundness had a very restricted effect in the project.

Fix `doXover` on the new semantics

---

.github/workflows/gobra.yml

The CI has been unreliable due to the race conditions that `--parallelizeBranches` seems to suffer from. This PR disables it, and disables the chopper (this last point slows us down, but drops our reliance on the chopper)

Disable chopper and parallelizeBranches in the CI
